# This pipeline gets triggered whenever there is commit to the master or release branch
# First it installs the SSH key to connect to tigress, then it logs in using SSH and runs the build (and publish) scripts

trigger:
  - master
  - release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '|1|VSzztJckGT3sQKgQAU/YaBkcZ3M=|1I9CC7gH+cNYHTcUQJN4SbeebTo= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAbnBKG3TZwbAc9QiLdPvMDxoKYe8+0OLcX7HC9ERCy/R0xOl7ETn9b0Gow+plAUqh3jz6fFPMvtWS7a+gbeDEY='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnEqeaID0MHNfKvGhhxTIDWPjPOxH/nFLKf28ncB4GjsrvwXYb2kKp0Xxo5JdWDeMddXaWl2KdQWqFYpK1BFfPXnClx4B+gKNG+c5t7EK8giKkO2ZtUtaoeiLBn4PAffXPCP0ebY/goojMaV0a9Syh3B6jyUUT+Lf+KyM94QEhCENJDyIjfmKmRZCwqcBa35VPSR78bWFgyMA/bUW5LWBWWYWwg03aRCdScBO7LbOOrAMnG7AB9gHQRqY4dV/98/Aix61No5c7PeVUKecB2ThHOnkMcN5lOKLs8Q1xxKQV8DuZBAsc/UEiWxvov14Dsz7C7qXFYGVjOfgHMpEdMnzCw== esbuilder@tigress'
    sshKeySecureFile: 'esbuilder_at_tigress_rsa'
  displayName: 'Install SSH keyfile for connection to build server'
- task: CmdLine@2
  inputs:
    script: 'ssh esbuilder@tigress.chem.washington.edu "source ~/.bash_profile; cd esbuildsys; perl build.pl;"'
  displayName: 'Run build scripts on build server'